name: Update README with GitHub Activity

on:
  schedule:
    - cron: "0 9 * * *" # corre una vez al día
  workflow_dispatch: # permite correrlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
